# Generated by Django 2.1.1 on 2019-10-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('fullname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('mobileno', models.CharField(max_length=30)),
                ('guardiancontactno', models.CharField(max_length=30)),
                ('course', models.CharField(max_length=20)),
            ],
        ),
    ]
