# Generated by Django 2.1.1 on 2019-10-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20191002_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='CODE', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default='description', max_length=200),
        ),
    ]
