# Generated by Django 2.1.1 on 2019-10-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20191004_0411'),
    ]

    operations = [
        migrations.CreateModel(
            name='SY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AY', models.CharField(max_length=20)),
            ],
        ),
    ]
