# Generated by Django 2.1.1 on 2019-10-03 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.EventName')),
            ],
        ),
        migrations.RenameField(
            model_name='semester',
            old_name='sem',
            new_name='semester',
        ),
        migrations.AddField(
            model_name='event_count',
            name='sem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Semester'),
        ),
        migrations.AddField(
            model_name='event_count',
            name='sy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.SY'),
        ),
    ]
