# Generated by Django 2.1.1 on 2019-10-03 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20191004_0454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_count',
            old_name='sem',
            new_name='semester',
        ),
    ]
