# Generated by Django 2.1.1 on 2019-10-04 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.EventName')),
            ],
        ),
        migrations.RemoveField(
            model_name='event_count',
            name='event',
        ),
        migrations.RemoveField(
            model_name='event_count',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='event_count',
            name='sy',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='date',
        ),
        migrations.AddField(
            model_name='attendance',
            name='isPresent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.EventDate'),
        ),
        migrations.DeleteModel(
            name='Event_Count',
        ),
    ]
