# Generated by Django 2.1.1 on 2019-11-17 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20191106_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='isPresent',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='sy',
        ),
        migrations.AddField(
            model_name='eventdate',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.Semester'),
        ),
        migrations.AddField(
            model_name='eventdate',
            name='sy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.SY'),
        ),
    ]
