# Generated by Django 2.1.1 on 2019-11-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_auto_20191117_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='logType',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventdate',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='eventdate',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
