# Generated by Django 2.1.1 on 2019-11-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_auto_20191117_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventdate',
            name='date',
        ),
        migrations.AddField(
            model_name='eventdate',
            name='eventdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
