# Generated by Django 2.1.1 on 2020-01-12 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_auto_20200112_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='event',
            new_name='eventDate',
        ),
    ]
