# Generated by Django 2.1.1 on 2020-01-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_auto_20200112_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdate',
            name='logType',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
