# Generated by Django 2.1.1 on 2020-01-15 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_eventdate_logtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='student',
            new_name='stud',
        ),
    ]
