# Generated by Django 2.1.1 on 2020-01-15 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_auto_20200115_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='stud',
            new_name='student',
        ),
    ]
