# Generated by Django 2.1.1 on 2020-02-09 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_auto_20200115_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=300)),
            ],
        ),
    ]
