# Generated by Django 2.1.1 on 2020-02-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_smslogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='smslogs',
            name='recipient',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
