# Generated by Django 2.1.1 on 2020-03-08 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_student_religion'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='isPresent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='eventDate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='student.EventDate'),
        ),
    ]
